# Generated by Django 6.0.3 on 2026-04-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, ' 2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
    ]
