# Generated by Django 6.0.3 on 2026-04-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
